### ISSUE TITLE
Allow using CLI in repos where origin is not codecrafters

### ISSUE THREAD

**Issue by aviau** [codecrafters-io/cli#12]
Hello,

Would it be possible to use the CLI in repos where codecrafters is not origin?

I like to use my own repo in github as my origin, and I have a remote "codecrafters" where I push to for the tests.

I would like to use `codecrafters test` in that repo, but it looks like this breaks it:
```
$ codecrafters test
Running tests on your codebase. Streaming logs...
create submission: failed to submit code to CodeCrafters. status code: 500, body
```

Would it be possible to add a `--remote` flag that I could use?

Or even a `codecrafters_cli.toml` config file where I can set my remote?

Looking at the code it looks like this should be supported, but it does not look like its working :(

It seems to create a bunch of `cli-test-` branches on github, so I guess that the `status 500` is an error from the codecrafters API after it was told to test a branch that was never pushed?

`.git/config` that **does** work:
```
[core]
    repositoryformatversion = 0
    filemode = true
    bare = false
    logallrefupdates = true
    ignorecase = true
    precomposeunicode = true
[remote "github"]
    url = git@github.com:aviau/bittorrent-rust-codecrafters.git
[remote "origin"]
    url = https://git.codecrafters.io/<censored_number>
```

`.git/config` that **does not** work:
```
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
	ignorecase = true
	precomposeunicode = true
[remote "origin"]
	url = git@github.com:aviau/bittorrent-rust-codecrafters.git
[remote "codecrafters"]
	url = https://git.codecrafters.io/<censored_number>
```

**Comment by rohitpaulk** [comment]
@aviau thanks for highlighting this! You’re right, this is _supposed_ to work, and the problem is likely that we’re not pushing the branch to the correct remote. Should be a quick fix - we’ll take a look this week!

**Comment by aviau** [comment]
Thanks for fixing this!
