### ISSUE TITLE
Add codecrafters-cli to nixpkgs

### ISSUE THREAD

**Issue by Builditluc** [codecrafters-io/cli#36]
I would like to add the codecrafters-cli to the [nixpkgs](https://github.com/NixOS/nixpkgs/) repo, so that people using nix can easily install and use the tool. I'm posting this issue to confirm this is allowed and/or wanted

**Comment by rohitpaulk** [comment]
Yep, would appreciate any help here!

**Comment by rohitpaulk** [comment]
For a bit of context on how our deployment currently works: 

- We currently support two modes of installation: brew & script. 
- The homebrew deployment happens here: https://github.com/codecrafters-io/cli/blob/e545daaf254de4641476c066a80cb570919a0661/.goreleaser.yml#L12-L25. 
- The script just points to https://github.com/codecrafters-io/cli/blob/main/install.sh

**Comment by Builditluc** [comment]
Hi, thanks for the info!

fyi, I created https://github.com/NixOS/nixpkgs/pull/332505, just have to wait till its merged!

**Comment by Builditluc** [comment]
It's merged now, should the documentation be updated to reflect the new installation method (would be happy to make a PR)?

**Comment by rohitpaulk** [comment]
Thanks @Builditluc! Yep, a PR would be great. Current docs are here: https://github.com/codecrafters-io/docs/blob/fcd17c66a977bf786cc8f850fc0ad6a16cf912a7/docs/cli/installation.mdx?plain=1. 

@Builditluc btw, how would updates work here? If we push a new version, how would we propagate an update to nixpkgs? Is it possible to automate this like with homebrew?

**Comment by Builditluc** [comment]
Once you release a new version, I update the package definition in nixpkgs and create a PR with the updated version. I subscribed to the repo, so I'll get notified whenever you release a new version

**Comment by rohitpaulk** [comment]
Gotcha. I want to see if we can automate this - @Builditluc could you share instructions for how the package definition is compiled? The hashes in particular.

**Comment by rohitpaulk** [comment]
@Builditluc thanks again for setting this up btw, I've applied a 1-year membership on the house to your CodeCrafters account so that you have access to all the challenges 🙂

**Comment by Builditluc** [comment]
As to my knowledge, you can't completely make it automatic. I use the [nix-update](https://github.com/Mic92/nix-update/) tool to update the package definition, but it cannot create pull requests and you'd still have to test the updated package.

Although there is the [r-ryantm](https://github.com/r-ryantm) bot which will automatically update the package after some time, due to it periodically looking for out-of-date packages
