### ISSUE TITLE
"make install" command fails

### ISSUE THREAD

**Issue by pooladkhay** [codecrafters-io/cli#6]
Hi,
I tried to build from source but `$ make install` fails with:
```
sudo go build -o /usr/local/bin/codecrafters cmd/codecrafters/main.go
# command-line-arguments
cmd/codecrafters/main.go:62:10: undefined: sentry
cmd/codecrafters/main.go:71:9: undefined: sentry
cmd/codecrafters/main.go:135:23: undefined: sentry
make: *** [Makefile:6: install] Error 1
```

Which can be easily fixed by importing `"github.com/getsentry/sentry-go"`.

I wonder if there are any particular reason behind that, otherwise I'd be happy to open a new Pull Request for it.

**Comment by rohitpaulk** [comment]
Sorry we missed this! I think this should be fixed now. We were in the middle of a refactor at the time
